# Generated by Django 3.0.2 on 2020-01-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_product_primary_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
